### ISSUE TITLE
Не устанавливается принтер

### ISSUE THREAD

**Issue by Fedotoff59** [Exomode/Printing.NET#3]
Добрый день.
В ходе тестирования не устанавливается принтер (все остальные компоненты устанавливаются)

В файле Printer.cs в строке 406 
if (All.Select(p => p.Name).Contains(Name)) Uninstall(serverName);
выбрасывает исключение:
| e | {"Значение не может быть неопределенным.\r\nИмя параметра: source"} | System.Exception {System.ArgumentNullException}

Если строку закомментировать, принтер устанавливается, но не подвязывается порт.
В чем может быть проблема?

**Comment by EXOMODE** [comment]
Приветствую!
Похоже, что-то не так с данными в процессе конфигурирования. Где-то теряется взаимосвязь. Рекомендую пошагово пройтись по всей цепочке вызовов ключевых методов и проверить значения передаваемых аргументов, а так же свойства экземпляров, которые они отдают на выходе. Где-то передаётся явный Null и скорее всего на последних двух шагах установки, когда идет работа непосредственно с принтерами и портами.
