### ISSUE TITLE
Не понимаю как использовать данную длл

### ISSUE THREAD

**Issue by APDATe** [Exomode/Printing.NET#7]
Добрый день!

ПОдскажите ато не понимаю где и как использовать эту длл 

для каких она целей?

если это драйвер виртуального принтера то не понимаю как его установить в систему (

**Comment by EXOMODE** [comment]
Вот подробная статья по этой библиотеке:
https://habr.com/ru/post/322322/

**Comment by APDATe** [comment]
я читал но так и не понял (

в общем создал вин форм приложение 

и повесил на кнопку событие 

в собитии прописал следующее

MonitorTests a = new MonitorTests();
            a.InstallTest();

            PortTests b = new PortTests();
            b.InstallTest();

            DriverTests c = new DriverTests();
            c.InstallTest();

            PrinterTests d = new PrinterTests();
            d.InstallTest();

а так же создал каталог d:\Printing Tests\ и положил в него скаченные файлы "d:\\Printing Tests\\mfilemon.dll"; и другие

но всегда получаю исключение при установке монитора PrintingException: Не найден указанный модуль

**Comment by APDATe** [comment]
пробовал  итак 

PrintingApiTests c = new PrintingApiTests();
            c.PrinterInstallationTest();

и так же получаю исключение в классе Port в строке 156  System.NullReferenceException: "Ссылка на объект не указывает на экземпляр объекта."

**Comment by APDATe** [comment]
Моя винда 10 x64 универсальный PPD качал x64

**Comment by APDATe** [comment]
ругалось на эту строчку
 if (!OpenPrinter($",XcvMonitor {Monitor.Name}", out IntPtr printerHandle, ref defaults)) throw new PrintingException(Marshal.GetLastWin32Error());

я переписал так теперь нет ругни но и нет ни принтера ни порта ничего (
if (!OpenPrinter($",XcvMonitor mfilemon", out IntPtr printerHandle, ref defaults)) throw new PrintingException(Marshal.GetLastWin32Error());

**Comment by APDATe** [comment]
разобрался спасибо
